root: true
env:
  node: true
extends:
  - airbnb-base
rules:
  valid-jsdoc: error
  arrow-parens:
    - error
    - as-needed
overrides:
  - files:
      - src/**/*.js
    env:
      browser: true
      node: false
    globals:
      module: false
  - files:
      - webpack.*.js
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
          peerDependencies: true